sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: db_heima_takeout
    username: root
    password: root
  ##阿里云OSS配置，用自己的账号信息替换下面的值
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHj8nqQh7sXo2m9Zt1
    access-key-secret: Zs1n9m8Xo2m9Zt1
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password: root
    database: 10
